service: lambda-test
provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
  ratings:
    handler: handler.ratings
    events:
      - http:
          path: /ratings
          method: get
          cors: true